<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- Generated by Avanquest Technology v:8.0. For information please visit: http://www.avanquestusa.com/ -->
<html lang="en">
<head>
	<title> Modify/Add </title>
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
	<meta http-equiv="Content-Style-Type" content="text/css;">
	<link rel="stylesheet" href="cmput391_g.css" type="text/css" media="screen,projection,print">	<!--// Document Style //-->
	<link rel="stylesheet" href="cmput391_015_p.css" type="text/css" media="screen,projection,print">	<!--// Page Style //-->
	<script src="cmput391_g.js" type="text/javascript"></script>		<!--// Document Script //-->
</head>
    
<%@ page import="cmput391.*" %>
<%@ page import="java.sql.*" %>


<body id="page">


<%@ page import="cmput391.*" %>
<%@ page import="java.sql.*" %>

<%
if(request.getParameter("rSubmit")!=null)
{
    checkUser(request, response, out);
    openPage(response, out);
}
%>

<%!public void checkUser(HttpServletRequest request, HttpServletResponse response, JspWriter out) {
	
	try {
			String username = (request.getParameter("username")).trim();
			String sql = "select * from users where user_name = '" + username + "'";
			Statement stmt = null;
			ResultSet rset = null;
			stmt = UserConnection.getConnection().getConn().createStatement();
			rset = stmt.executeQuery(sql);
			String trueuser = "";
			while (rset != null && rset.next()) {
				trueuser = (rset.getString(1)).trim();
			}
			if (username.equals(trueuser)) {
				out.println("<p><b> This user name already exists! </b></p>");
			} 
			if (username.equals("")) {
				out.println("<p><b> Username field not filled! </b></p>");
			}
			if (!username.equals("") && !username.equals(trueuser)) {
				checkPassword(username,request, response, out);
			}
		} catch (Exception ex) {
			System.out.println("" + ex.getMessage() + "");
		}
	}
	
	
	public void checkPassword(String username, HttpServletRequest request, HttpServletResponse response, JspWriter out) {
		try {
		String password = (request.getParameter("password")).trim();
		String retypepassword = (request.getParameter("retypepassword")).trim();
		if(!password.equals(retypepassword)){
			out.println("<p><b> Passwords dont match! </b></p>");
		}
		if (password.equals("")) {
			out.println("<p><b> Password field not filled! </b></p>");
		}
		if (password.equals(retypepassword) && !password.equals("")){
			checkEmail(username, password, request, response, out);
		}

		} catch (Exception ex) {
		System.out.println("" + ex.getMessage() + "");
		}
	}
	
	public void checkEmail(String username, String password, 
			HttpServletRequest request, HttpServletResponse response, JspWriter out) {
		try {
		
		String email = (request.getParameter("email"));
		String sql = "select * from persons where email = '" + email + "'";
		Statement stmt = null;
		ResultSet rset = null;

			stmt = UserConnection.getConnection().getConn().createStatement();
			rset = stmt.executeQuery(sql);

			String trueEmail = "";

			while (rset != null && rset.next()) {
				trueEmail = (rset.getString(5)).trim();
			}

			if (email.equals(trueEmail)) {
				out.println("<p><b> This Email is already registered by another user! </b></p>");
			}
			if (email.equals("")) {
				out.println("<p><b> Email field not filled! </b></p>");
			}
			if (!email.equals(trueEmail) && !email.equals("")) {
				registerUser(username, password, email, request, response, out);
			}
		} catch (Exception ex) {
			System.out.println("" + ex.getMessage() + "");
		}

	}
	
	
	public void registerUser(String username, String password, String email, 
			HttpServletRequest request, HttpServletResponse response, JspWriter out) {
		try {
		
		String comboBox = (request.getParameter("combo_box"));
		
		if(comboBox.equals("1. Patient")){
			comboBox = "p";
		}
		if(comboBox.equals("2. Doctor")){
			comboBox = "d";
		}
		if(comboBox.equals("3. Radiologist")){
			comboBox = "r";
		}
		if(comboBox.equals("4. Admin")){
			comboBox = "a";
		}
		
		try{
		String sql = "insert into users values ('" +username+ "','" +password+ "', '" +comboBox+ "', SYSDATE)";
		Statement stmt = null;
		ResultSet rset = null;

			stmt = UserConnection.getConnection().getConn().createStatement();
			rset = stmt.executeQuery(sql);
			UserConnection.getConnection().getConn().commit();
		} catch (Exception ex) {
			System.out.println("" + ex.getMessage() + "");
		}
		
		String firstname = (request.getParameter("firstname"));
		String lastname = (request.getParameter("lastname"));
		String address = (request.getParameter("address"));
		String phone = (request.getParameter("phone"));
		try {
		String sql2 = "insert into persons values ('" +username+ "', '" +firstname+ "', '" +lastname+ "','" +address+ "', '" +email+ "', '" +phone+ "')";
		Statement stmt = null;
		ResultSet rset = null;
		
			stmt = UserConnection.getConnection().getConn().createStatement();
			rset = stmt.executeQuery(sql2);
			UserConnection.getConnection().getConn().commit();
		} catch (Exception ex) {
			System.out.println("" + ex.getMessage() + "");
		}
		
		}catch (Exception ex) {
			System.out.println("" + ex.getMessage() + "");
		}
	}
	
	public void openPage(HttpServletResponse response, JspWriter out) {
		try{
			response.sendRedirect("Login.jsp");
		}catch (Exception ex) {
			System.out.println("" + ex.getMessage() + "");
		}
	}
	%>


<form method="post">
	<input id="e24" class="cc49" type="text" name="text_box" value="userName" size="23">
	<input id="e23" class="cc49" type="password" name="password" size="23">
	<input id="e22" class="cc50" type="button" value="Register" onclick="alert('Button')">
	<div id="e21" class="cc50">
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;UserName:
	</div>
	<div id="e20" class="cc50">
		&nbsp;&nbsp;Password:
	</div>
	<div id="e19" class="cc51">
		Modify/Add:
	</div>
	<input id="e18" class="cc49" type="password" name="password" size="23">
	<div id="e17" class="cc50">
		Retype Password:
	</div>
	<div id="e16" class="cc50">
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Class:
	</div>
	<div id="e15" class="cc50">
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Email:
	</div>
	<input id="e14" class="cc49" type="text" name="text_box" value="FirstName" size="23">
	<div id="e13" class="cc50">
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;First Name:
	</div>
	<input id="e12" class="cc49" type="text" name="text_box" value="lastName" size="23">
	<div id="e11" class="cc50">
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Last Name:
	</div>
	<input id="e10" class="cc49" type="text" name="text_box" value="phone" size="23">
	<div id="e9" class="cc50">
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Phone:
	</div>
	<input id="e8" class="cc49" type="text" name="text_box" value="address" size="23">
	<div id="e7" class="cc50">
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Address:
	</div>
	<input id="e6" class="cc49" type="text" name="text_box" value="email" size="23">
	<select id="e5" class="cc52" size="1" name="combo_box" onchange="alert('Combo_Box'+'['+this.selectedIndex+']')">
	<option> 1. Patient</option>
	<option> 2. Doctor</option>
	<option> 3. Radiologist</option>
	<option> 4. Admin</option>
	</select>
	<input id="e4" class="cc49" type="text" name="text_box" size="23">
	<input id="e3" class="cc49" type="text" name="text_box" size="23">
	<div id="e2" class="cc50">
		Doctor Name:
	</div>
	<div id="e1" class="cc50">
		&nbsp;Patient Name:
	</div>
</form>
</body>
</html>